# Generated by Django 3.0 on 2024-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_etl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(max_length=100)),
                ('index_name', models.CharField(max_length=100)),
                ('dep_info', models.CharField(max_length=100)),
                ('sql_info', models.TextField()),
            ],
        ),
    ]
