# Generated by Django 4.2 on 2024-04-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='col_type_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mysql_col_type', models.CharField(max_length=100)),
                ('map_col_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='index_etl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(max_length=100)),
                ('index_name', models.CharField(max_length=100)),
                ('dep_info', models.CharField(max_length=100)),
                ('sql_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('column_type', models.CharField(max_length=100, null=True)),
                ('column_length', models.IntegerField(blank=True, null=True)),
                ('hive_column_type', models.CharField(max_length=100)),
                ('primary_key', models.IntegerField(default=0)),
                ('partition_key', models.IntegerField(default=0)),
            ],
        ),
    ]
